<?php

namespace AppBundle\Repository;

/**
 * MuseumFeatureRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MuseumFeatureRepository extends \Doctrine\ORM\EntityRepository
{
}
